language: erlang
otp_release:
    - 18.3

sudo: required

services:
    - docker

before_install:
    - make test-environment
    - docker ps
    - docker logs zookeeper
    - docker logs mesos-master
    - docker logs mesos-slave

after_script:
    - docker ps
    - docker logs zookeeper
    - docker logs mesos-master
    - docker logs mesos-slave


