language: erlang
otp_release:
    - 17.5
    - 18.0

sudo: required

services:
    - docker

before_install:
    - make test-environment
    - docker ps
    - docker logs zookeeper
    - docker logs mesos-master
    - docker logs mesos-slave 
